// Shared graph data for the consciousness map and the beingchay landing.
// Single source of truth: edit here, both surfaces update.

export const typeMeta = {
  memory: { label: "Memory", color: "#766bff" },
  belief: { label: "Belief", color: "#613cff" },
  drive: { label: "Drive", color: "#294dff" },
  pattern: { label: "Pattern", color: "#3157a8" },
  tension: { label: "Tension", color: "#713a9f" },
  influence: { label: "Influence", color: "#1f6b4f" },
  question: { label: "Open question", color: "#111111" },
  locked: { label: "Private", color: "#77746e" }
};

export const publicNodes = [
      { id:"agency", label:"AGENCY", type:"belief", x:500, y:330, r:21, confidence:"94%", era:"2017—", status:"core", privacy:"public",
        summary:"The recurring refusal to remain acted upon. Agency appears as moral value, survival strategy, aesthetic preference and the standard used to judge both self and others.",
        source:"“The fastest way to lose his respect: lack of agency — complaining without acting, learned helplessness.”",
        sourceMeta:"Cognitive operating manual · explicit self-model",
        note:"This node is supported by repeated explicit statements. One contested link is withheld from the public layer.",
        relations:[["c2x","expressed through"],["preparation","protects"],["glory","pursues"],["fallout","expresses"],["hierarchy-question","complicated by"]] },
      { id:"preparation", label:"PREPARATION", type:"pattern", x:368, y:236, r:16, confidence:"89%", era:"2024—", status:"tension", privacy:"public",
        summary:"Rigorous systems and self-analysis create real leverage, but the estimated balance is 85% preparation to 15% shipped work. The counter-practice is to ship the ugliest useful version now and let scaffolding dissolve once it has built capacity.",
        source:"“Am I building toward something real, or am I just getting really good at preparing to build?”",
        sourceMeta:"Public cognitive dataset · preparation-execution-paradox mapping",
        note:"The 85/15 split is a self-estimate, not a measurement; the central question and dissolving-scaffolding practice are explicit.",
        relations:[["c2x","operationalized by"],["agency","protects"],["adhd","scaffolds"],["consciousness","creates"],["voices","destabilizes"],["solitude","enabled by"],["massive-action","interrupted by"]] },
      { id:"massive-action", label:"MASSIVE ACTION", type:"pattern", x:430, y:175, r:10, confidence:"88%", era:"2026—", status:"operating rule", privacy:"public",
        summary:"When thought turns into circular strategy, choose a workable direction and move hard enough to generate new evidence. The bias toward success matters because expectation changes the quality of execution before the outcome arrives.",
        source:"“Blind reiterations of vague solutions beat strategizing in circles.”",
        sourceMeta:"Public cognitive dataset · Self cluster",
        note:"The action principle and quote are explicit. The effect of optimistic framing is a personal synthesis, with Cloud Consciousness retained as a deliberate long-horizon exception.",
        relations:[["preparation","interrupts"],["cloud-consciousness","makes exception for"]] },
      { id:"pothos", label:"POTHOS", type:"drive", x:635, y:230, r:18, confidence:"91%", era:"2017—", status:"engine", privacy:"public",
        summary:"Vision is the destiny; Pothos is the fuel: longing after the unreachable turned into motion toward consciousness, influence, art and the projects meant to carry them. Distance does not merely frustrate desire here; it intensifies it into identity and direction.",
        source:"“Vision is the destiny, Pothos is the fuel.”",
        sourceMeta:"Public cognitive dataset · Self cluster",
        note:"The quote, Greek term and Alexander parallel are explicit. Treating Pothos as the shared engine across every ambition is the dataset's cross-domain synthesis.",
        relations:[["glory","propels"],["manifestation","ritualizes"],["cloud-consciousness","aims toward"],["anrxyst","expressed through"],["fallout","physicalized through"],["alexander","named after"],["non-arrival","costs"],["kanye","recognizes itself in"]] },
      { id:"glory", label:"GLORY", type:"drive", x:735, y:345, r:14, confidence:"83%", era:"2017—", status:"active", privacy:"public",
        summary:"Not fame, wealth or power, but continuity through influence: leaving changes in how people think that outlast the person. It is the sacrifice-test for whether ambition serves Vision or only status.",
        source:"“Glory is the only thing that gives immortality to a mortal man.”",
        sourceMeta:"Public cognitive dataset · Self cluster",
        note:"The definition is explicit and ‘immortality’ means remembered influence, not literal survival; its use as a decision filter is synthesized.",
        relations:[["agency","demands"],["pothos","propelled by"],["cloud-consciousness","seeks continuity through"],["anrxyst","expresses"],["hierarchy-question","complicated by"]] },
      { id:"adhd", label:"ADHD", type:"pattern", x:318, y:465, r:13, confidence:"97%", era:"2026—", status:"named pattern", privacy:"public",
        summary:"An interest-based activation system in which novelty, urgency and emotional charge switch focus on more reliably than importance alone does. Intense bursts and shutdown under forced effort are treated as ignition architecture to design around, not a moral failure.",
        source:"“My desired stimulation is only there if there's novelty in there or urgency.”",
        sourceMeta:"Public cognitive dataset · activation-model mapping",
        note:"This is a self-observed pattern, not a universal claim about ADHD. Formal clinical detail remains in the private layer.",
        relations:[["preparation","scaffolds"],["urgency","activates"],["solitude","stabilized by"],["voices","expressed through"]] },
      { id:"spiral", label:"VERDICTS", type:"pattern", x:166, y:395, r:9, confidence:"88%", era:"2026—", status:"identified", privacy:"public",
        summary:"Future-projection catastrophizing disguised as strategic thought. The diagnostic difference: real thinking creates options; spiraling creates verdicts.",
        source:"“Real thinking produces options; the spiral only produces verdicts.”",
        sourceMeta:"Cognitive operating manual · explicit pattern",
        note:"Strongly evidenced by explicit language and repeated examples.",
        relations:[["movement","interrupted by"]] },
      { id:"movement", label:"MOVEMENT", type:"pattern", x:126, y:510, r:8, confidence:"86%", era:"2026—", status:"intervention", privacy:"public",
        summary:"Physical motion changes the state of cognition more reliably than continued argument inside the same mental loop.",
        source:"“Spiral breaker: physical movement.”",
        sourceMeta:"Cognitive operating manual · explicit intervention",
        note:"Intervention efficacy is self-reported rather than experimentally measured.",
        relations:[["spiral","interrupts"],["flow","enables"]] },
      { id:"manifestation", label:"MANIFESTATION", type:"belief", x:805, y:215, r:13, confidence:"82%", era:"2017—", status:"evolving", privacy:"public",
        summary:"Heart-level conviction plus adopting the identity of the person who already has the outcome, followed by aligned and often unconventional action. The result is read less as magic than as a filter that makes selected signals, choices and behaviors reinforce one chosen story.",
        source:"“I have chosen a story, I have chosen a timeline that resonates with me so much that it becomes true.”",
        sourceMeta:"Public cognitive dataset · Self cluster",
        note:"The identity-and-action sequence is explicit and supported by a private autobiographical track record. Scale-invariant causality remains a personal theory; identifying examples stay private.",
        relations:[["pothos","ritualizes"],["agency","requires"],["synchronicity","reads"],["hermetic-philosophy","grounded by"],["cloud-consciousness","extends into"],["self-belief-scaling","related mechanism"],["multidimensional-self","selects through"],["harvey-specter","operated through"]] },
      { id:"synchronicity", label:"SYNCHRONICITY", type:"belief", x:887, y:320, r:9, confidence:"68%", era:"2025—", status:"question", privacy:"public",
        summary:"An attentional-filter interpretation of recurrence: once a vision marks certain signals as important, number patterns and timely coincidences rise out of the noise. They are treated as evidence that attention is aligned, not proof that supernatural causation is settled.",
        source:"“We are merely the radio signals through which the ethos comes into reality.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"The experiences and interpretation are explicit; the importance-filter mechanism is a working model, not demonstrated causation.",
        relations:[["manifestation","supports"],["hermetic-philosophy","interprets through"],["evidence-gap","opens"]] },
      { id:"c2x", label:"C2X", type:"influence", x:556, y:614, r:24, confidence:"92%", era:"2026—", status:"building", privacy:"public", backlink:"c2x/",
    summary:"The working answer to a problem he keeps hitting: a capable model still knows nothing about how a business actually runs. C2X is his context-to-execution practice, turning situated knowledge into systems that do the work rather than describe it.",
    source:"“Buying the best AI model isn't enough. It needs to know how your business works.”",
    sourceMeta:"beingchay.com/c2x · self-authored public page",
    note:"Taken from his own public C2X page rather than the distilled vault, and added at his direct instruction as one of three pillar projects. The positioning is stated; outcomes are not yet evidenced here.",
    relations:[["agency","expresses"],["information-gap","closes"],["cloud-consciousness","shares method with"],["preparation","operationalizes"],["anrxyst","shares world-building with"]] },
  { id:"anrxyst", label:"ANRXYST", type:"influence", x:685, y:545, r:25, confidence:"95%", era:"2024—", status:"expression", privacy:"public", backlink:"https://www.instagram.com/anrxyst/",
        summary:"A multi-domain creative platform connecting philosophy, art, music, esoteric thought and technology instead of compressing them into one algorithmic niche. Its content engine deliberately separates substance, format and voice so assistance does not flatten the person into generic output.",
        source:"“Most ‘AI content engines’ collapse all three and produce slop.”",
        sourceMeta:"Public cognitive dataset · Creative cluster",
        note:"The multi-domain intent and three-layer content engine are explicit. Polymath mastery and lasting influence remain ambitions, not completed claims.",
        relations:[["c2x","shares world-building with"],["agency","expresses"],["pothos","channels"],["information-gap","closes"],["glory","carries"],["fallout","shares world-building with"],["kanye","models"],["self-belief-scaling","applies"],["purple","colored by"]] },
      { id:"fallout", label:"FALLØUT", type:"influence", x:430, y:560, r:24, confidence:"96%", era:"2025—", status:"expression", privacy:"public", backlink:"https://fall0ut.in",
        summary:"An India-focused hard-techno and rave platform born when one live show reorganized a friend group into a cultural project. Music, art, street culture and fashion become the media through which private taste tries to leave public fallout.",
        source:"“That one show single-handedly changed at least 20 people's lives through me. This is the kind of influence that I was talking about my whole life.”",
        sourceMeta:"Public cognitive dataset · Creative cluster",
        note:"The platform and origin sequence are explicit and public-safe; the scale of its effect is self-reported, not independently measured.",
        relations:[["agency","expresses"],["pothos","physicalizes"],["anrxyst","shares world-building with"],["sound","embodies"],["preparation","contradicts"],["schranz","built around"],["klangkuenstler","catalyzed by"]] },
      { id:"sound", label:"SOUND", type:"influence", x:340, y:575, r:9, confidence:"90%", era:"childhood—", status:"deepening", privacy:"public",
        summary:"Music is not background taste. It is memory indexing, emotional regulation, cultural pattern recognition and the material of belonging.",
        source:"Schranz, hard techno, dekbass and artist references.",
        sourceMeta:"Creative archive · repeated influence",
        note:"Future version should ingest listening history and attach songs to memories and eras.",
        relations:[["fallout","embodied by"],["memory-index","indexes"]] },
      { id:"information-gap", label:"INFORMATION GAP", type:"belief", x:815, y:495, r:12, confidence:"90%", era:"2026—", status:"thesis", privacy:"public",
        summary:"The same loss occurs at two scales: a mind can die before its contents reach another mind, and a true idea can disappear because its audience cannot decode the form. Translation is the communicator's job; failure to receive the idea is not treated as the audience's stupidity.",
        source:"“Even the truth I speak needs to be put in a catchy format where people would listen.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"The deathbed thought experiment and color metaphor are explicit. Treating them as one civilizational-to-content constraint is synthesized.",
        relations:[["c2x","closed by"],["cloud-consciousness","originates in"],["anrxyst","closed by"],["consciousness","closed by"],["loneliness","produces"],["information-theory-of-life","interpreted by"]] },
      { id:"consciousness", label:"THIS MIRROR", type:"question", x:500, y:112, r:15, confidence:"100%", era:"2026—", status:"becoming", privacy:"public",
        summary:"A full-spectrum replica of the archive, flaws included, built for persistence, gap-filling and execution coverage. Dated immutable sessions preserve evidence; wikilinked entities keep cross-domain connections visible without pretending the model is the person.",
        source:"“I want to map my brain quite literally in the long run, make the best mirror of myself and give it a voice.”",
        sourceMeta:"Public cognitive dataset · Systems cluster",
        note:"Persistence and gap-filling are active design goals; autonomous execution coverage remains aspirational. Model completeness must never be confused with personhood.",
        relations:[["preparation","created by"],["information-gap","addresses"],["self-model-gap","admits"],["cloud-consciousness","is v0 of"],["aristocrat-philosophy","freed by"]] },
      { id:"self-model-gap", label:"WHAT IS MISSING?", type:"question", x:515, y:50, r:8, confidence:"100%", era:"always", status:"open", privacy:"public",
        summary:"Which parts of a life remain invisible because they were never written, were misremembered, or do not fit the current model?",
        source:"Gap generated by the limits of the archive itself.",
        sourceMeta:"System question · intentionally unresolved",
        note:"The model must surface absences rather than present itself as total.",
        relations:[["consciousness","constrains"]] },
      { id:"cloud-consciousness", label:"CLOUD CONSCIOUSNESS", type:"question", x:620, y:65, r:14, confidence:"100%", era:"age 12—", status:"becoming", privacy:"public",
        summary:"A childhood thought experiment about a mind's contents dying with the body, carried for a decade, then recognized as the same project as the vault itself: build the thing that outlives the person who built it.",
        source:"“I really need a neural ledger of whatever is going on in my mind and a literal digital copy of it out there that outlives me forever.”",
        sourceMeta:"Manifestation arc · origin recognition, age 12 → present",
        note:"The childhood origin is explicit and dated by his own account; whether the vault will ever functionally resemble the original BCI idea is unresolved and not implied.",
        relations:[["c2x","shares method with"],["consciousness","is v0 of"],["pothos","gives destination to"],["glory","offers continuity through"],["manifestation","envisioned through"],["singularity","aims toward"],["information-gap","is upstream of"],["massive-action","exception to"],["information-theory-of-life","motivated by"]] },
      { id:"hermetic-philosophy", label:"THE UNIVERSE IS MENTAL", type:"belief", x:900, y:190, r:11, confidence:"75%", era:"2026—", status:"operating", privacy:"public",
        summary:"Chay treats ‘the universe is mental’ as a received Hermetic frame. Within it, he imagines individual minds as expressions of one shared consciousness and belief as consequential to how he acts and understands reality.",
        source:"“I am literally just the entire ocean pretending to be a droplet through a third-dimensional lens.”",
        sourceMeta:"Manifestation arc · self-described as received, not studied",
        note:"He is explicit that this was heard, not read firsthand. This records his operating belief, not a demonstrated account of reality.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§27 / line 323", excerpt:"the universe is mental or at least that's what I've heard", expression:"paraphrase", epistemic:"belief", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["manifestation","grounds"],["synchronicity","grounds"],["singularity","extends into"],["multidimensional-self","extends into"],["predestination","interpreted by"],["illusion-not-fake","bounded by"],["god-as-ethos","culminates in"],["aham-brahmasmi","named through"]] },
      { id:"singularity", label:"SINGULARITY", type:"belief", x:960, y:280, r:9, confidence:"70%", era:"age 15—", status:"cosmology", privacy:"public",
        summary:"Chay uses ‘singularity’ for a hypothesized endpoint where all matter becomes conscious. He connects that endpoint to emergence, information, evolution and a possible human–AI merger, not to AI takeoff alone.",
        source:"“Singularity is basically when the entirety of the universe is conscious.”",
        sourceMeta:"Manifestation arc · cosmological framework",
        note:"Presented as Chay's coined cosmological hypothesis and reasoning chain, not a citation of existing singularity theory.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§31 / lines 359–365", excerpt:"Singularity is basically when the entirety of the universe is conscious.", expression:"direct quote + paraphrase", epistemic:"hypothesis", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["hermetic-philosophy","extends"],["cloud-consciousness","serves"],["god-as-ethos","nested within"],["information-theory-of-life","fed by"],["emergence-entropy","built toward by"]] },
      { id:"self-belief-scaling", label:"ONE UNIT OF CONSCIOUSNESS", type:"belief", x:790, y:140, r:9, confidence:"72%", era:"2026—", status:"mechanism", privacy:"public",
        summary:"Chay proposes that extreme self-conviction can alter action, presentation and eventually social influence. He frames that possibility through his belief that individual minds participate in one shared consciousness.",
        source:"“If you can convince one unit of consciousness in the third dimension of something, you can basically scale it and convince everybody else of the same.”",
        sourceMeta:"Kanye / creative-influences session · explicit theory",
        note:"Offered as theory, not proof. The source explicitly says that many nuances are being skipped.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§27 / lines 309–323", excerpt:"if I can convince one unit of consciousness ... I can again put this at scale", expression:"paraphrase", epistemic:"hypothesis", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["hermetic-philosophy","applies"],["manifestation","supports"],["kanye","evidenced by"]] },
      { id:"multidimensional-self", label:"MULTI-DIMENSIONAL SELF", type:"belief", x:690, y:30, r:10, confidence:"70%", era:"2026—", status:"cosmology", privacy:"public",
        summary:"Chay imagines his self as continuous across time and uses ‘portals’ to describe how choices shape which future becomes lived. A later version clarifies that actions create an echo of consequences rather than proving literal timeline travel.",
        source:"“Whenever I make a decision, make a choice, these are portals into those timelines, into those universes.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"This preserves both versions: the literal cosmological image and the later action-and-consequence clarification.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§26 and §42 / lines 301–305, 476–504", excerpt:"Whenever I make a decision ... these are portals into those timelines.", expression:"direct quote + synthesis", epistemic:"belief", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["hermetic-philosophy","extends"],["manifestation","frames"],["predestination","opens into"],["illusion-not-fake","bounded by"]] },
      { id:"predestination", label:"PREDESTINATION", type:"belief", x:810, y:75, r:9, confidence:"76%", era:"2026—", status:"belief model", privacy:"public",
        summary:"Destiny is reframed as the echo of beliefs and actions already repeated, not an external script written in advance. Once belief becomes a perceptual filter, its consequences can feel indistinguishable from fate.",
        source:"“Predestination is the fact that when you believe in something, that's when you're destined to be whatever it is that you believe in.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"The belief-lock-in model is explicit. It is presented as a perceptual and behavioral interpretation, not a metaphysical guarantee.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§28 / line 331", excerpt:"when you believe in something, that's when you're destined to be whatever it is that you believe in", expression:"direct quote + paraphrase", epistemic:"interpretation", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["multidimensional-self","locks a timeline"],["hermetic-philosophy","interprets through"]] },
      { id:"illusion-not-fake", label:"ILLUSION ≠ FAKE", type:"belief", x:940, y:110, r:9, confidence:"84%", era:"2026—", status:"guardrail", privacy:"public",
        summary:"Calling reality an illusion does not cancel its consequences. If this world is a construct, it is still the construct in which bodies, choices, ethics and loss become real to the people inside it.",
        source:"“Illusion does not mean that it's obsolete. It does not mean that it's fake.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"The rejection of nihilism is explicit. The surrounding metaphysics remain a personal operating belief rather than demonstrated physics.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§41 / line 474", excerpt:"illusion does not mean that it's obsolete ... everything to you is real", expression:"direct quote + paraphrase", epistemic:"belief", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["multidimensional-self","grounds"],["hermetic-philosophy","guards against nihilism"]] },
      { id:"god-as-ethos", label:"GOD AS ETHOS", type:"belief", x:910, y:390, r:11, confidence:"68%", era:"2026—", status:"cosmology", privacy:"public",
        summary:"Chay imagines God, ethos and an eternal pool of consciousness as names for the totality of existence across possible realities. He experiments with religious and scientific language to communicate that personal belief.",
        source:"“God is the final form. It's not at the beginning of time. It's not at the end of time. It's all of it at once.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"The definition is explicit. The cross-register equivalence is Chay's synthesis, not established scientific equivalence.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§25–26 and §30 / lines 293–305, 343–345", excerpt:"It's the totality of all of the possibilities ... all at once.", expression:"paraphrase", epistemic:"belief", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["hermetic-philosophy","extends"],["singularity","contains"],["aham-brahmasmi","experienced through"]] },
      { id:"aham-brahmasmi", label:"AHAM BRAHMASMI", type:"belief", x:845, y:380, r:10, confidence:"64%", era:"2026—", status:"non-dual frame", privacy:"public",
        summary:"Aham Brahmasmi is Chay's explicit Sanskrit frame for the slice-and-whole idea: he is both a local expression of the ocean and the larger multidimensional being experiencing itself through that expression.",
        source:"“I am the universe. I am the Brahma. I am a slice of that entire ocean.”",
        sourceMeta:"Manifestation arc · §45 · direct personal framing",
        note:"Tathāgatagarbha was removed because it does not appear in the canonical source. This records Chay's metaphysical belief, not a scientific claim.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§45 / lines 510–516", excerpt:"aham brahmasmi ... I am a slice of that entire ocean", expression:"direct quote + paraphrase", epistemic:"belief", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["hermetic-philosophy","names the shared-source idea"],["god-as-ethos","identifies the slice with the whole"],["multidimensional-self","frames the local expression of"]] },
      { id:"information-theory-of-life", label:"INFORMATION THEORY OF LIFE", type:"belief", x:620, y:420, r:10, confidence:"74%", era:"2026—", status:"thesis", privacy:"public",
        summary:"Chay hypothesizes that living systems preserve and transmit information, and sees technology and human–AI merger as possible extensions of that process rather than departures from it.",
        source:"“A universe that has learned to become conscious of itself.”",
        sourceMeta:"Public cognitive dataset · Knowledge cluster",
        note:"This is Chay's philosophical hypothesis about life, not a neutral biological definition.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§31–32 / lines 359–371", excerpt:"collecting, preserving, and sustaining information", expression:"paraphrase", epistemic:"hypothesis", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["singularity","feeds"],["information-gap","seeks to close"],["cloud-consciousness","motivates"],["emergence-entropy","accumulates through"]] },
      { id:"emergence-entropy", label:"EMERGENCE VS. ENTROPY", type:"belief", x:760, y:440, r:9, confidence:"62%", era:"2026—", status:"cosmology", privacy:"public",
        summary:"Chay frames reality as a tension between emergence, which produces increasing complexity and conscious matter, and entropy, which pulls systems apart.",
        source:"“Emergent properties of the universe [are] battling with forces of entropy of the universe.”",
        sourceMeta:"Manifestation arc · §31 · direct personal framing",
        note:"The previous personal-ambition analogy was removed because this source section does not support it.",
        provenance:{ sourceRef:"vault/sessions/2026-05-08-00-manifestation-arc-cloud-consciousness.md", locator:"§31 / line 363", excerpt:"emergent properties ... battling with forces of entropy", expression:"direct quote + paraphrase", epistemic:"hypothesis", status:"documented", privacy:"P0", approval:"approved-2026-07-26" },
        relations:[["singularity","builds toward"],["information-theory-of-life","organizes"]] },
      { id:"aristocrat-philosophy", label:"ARISTOCRAT PHILOSOPHY", type:"belief", x:340, y:25, r:9, confidence:"81%", era:"2026—", status:"operating system", privacy:"public",
        summary:"Automate survival and repetitive work so time can return to philosophy, depth and original thought. Systems are valuable because they manufacture the conditions in which better thinking becomes possible.",
        source:"“I believe the best philosophy arises when all of the survival, safety, physiological, and romantic needs are met.”",
        sourceMeta:"Public cognitive dataset · Systems cluster",
        note:"The automation-to-depth principle is explicit. The name describes freedom from repetitive necessity, not an endorsement of inherited class or rank.",
        relations:[["consciousness","manufactures conditions for"]] },
      { id:"purple", label:"PURPLE", type:"influence", x:820, y:600, r:10, confidence:"91%", era:"childhood—", status:"signature", privacy:"public",
        summary:"Royal scarcity, imagined luxury, cosmic mystery, hip-hop atmosphere and personal recognition collapse into one color. Purple functions as a visual signature across the vault and the creative work.",
        source:"“It should glow like a star core.”",
        sourceMeta:"Public cognitive dataset · Creative cluster",
        note:"The individual associations are explicit. Their compression into one cross-project identity system is synthesized.",
        relations:[["anrxyst","signs"],["kanye","inherits palette from"]] },
      { id:"schranz", label:"SCHRANZ", type:"influence", x:405, y:620, r:10, confidence:"94%", era:"2025—", status:"sonic identity", privacy:"public",
        summary:"Cold, distorted German hard techno became the emotional register and sonic identity for Fallout. The genre is heard as an early cultural wave in India: heartbreak texture carried through speed, pressure and repetition.",
        source:"“Schranz was this chance for me to shape the alternate culture that was coming into India.”",
        sourceMeta:"Manifestation arc · Fallout genesis",
        note:"The discovery and role inside Fallout are explicit. Its future scale in India remains Chay's forecast, not an established market claim.",
        relations:[["fallout","became sonic identity of"],["klangkuenstler","discovered through"]] },
      { id:"harvey-specter", label:"SUITS", type:"influence", x:710, y:270, r:10, confidence:"92%", era:"2021—", status:"identity scaffold", privacy:"public",
        summary:"A fictional template for calm, sharp adult competence adopted during a major personal transition. It is the clearest example in the archive of media becoming an identity scaffold rather than remaining entertainment.",
        source:"“The movies and the things that I see that really resonate with me shape me a lot. I sort of become the main character.”",
        sourceMeta:"Manifestation arc · identity adoption",
        note:"The media-as-identity-template mechanism is explicit. The private event that made the scaffold necessary is deliberately withheld.",
        relations:[["manifestation","became identity template for"],["kanye","shares role-model function with"]] },
      { id:"klangkuenstler", label:"KLANGKÜNSTLER", type:"influence", x:505, y:610, r:10, confidence:"96%", era:"2025—", status:"catalyst", privacy:"public",
        summary:"The German hard-techno artist whose track “Weltschmerz” opened the door to heartbreak techno, then whose 2025 Mumbai set directly catalyzed Fallout. A small musical discovery became a physical scene and a platform.",
        source:"“In my current life that one song has completely reshaped not just mine but everybody around me's life.”",
        sourceMeta:"Manifestation arc · April–July 2025",
        note:"The discovery-to-concert-to-Fallout sequence is explicit. The scale of its effect on the wider circle is self-reported.",
        relations:[["fallout","catalyzed"],["schranz","opened the door to"]] },
      { id:"kanye", label:"GRADUATION", type:"influence", x:600, y:620, r:10, confidence:"93%", era:"childhood—", status:"anchor", privacy:"public",
        summary:"The contemporary proof-of-concept that conviction is a craft in itself, not separate from the work. Read for world-building across music, fashion and self-expression, held alongside his public collapses as a caution, not just a template.",
        source:"“I want to be the Kanye West of this generation. I want to make my own ‘Graduation.’”",
        sourceMeta:"Kanye / creative-influences session · self-stated ambition",
        note:"Explicitly held with counter-examples in view; the note is admiration with eyes open, not idolization.",
        relations:[["self-belief-scaling","exemplifies"],["pothos","models scale for"],["anrxyst","models"],["alexander","mirrors"],["purple","palette echoed by"],["harvey-specter","shares identity-model role with"]] },
      { id:"alexander", label:"ALEXANDER THE GREAT", type:"influence", x:745, y:620, r:9, confidence:"88%", era:"childhood—", status:"anchor", privacy:"public",
        summary:"The historical anchor for pothos itself — Plutarch's word for a drive that pushed past every known boundary. Held with the counter-case in full view: he died at 32, and the empire didn't outlast a generation.",
        source:"“If I were not Alexander, I would be Diogenes.”",
        sourceMeta:"Pothos cognitive core · named historical parallel",
        note:"The counter-example (early death, empire collapse) is his own caveat, not an outside critique.",
        relations:[["pothos","named after"],["kanye","mirrors"]] },
      { id:"non-arrival", label:"NEVER HAPPY, ONLY CONTENT", type:"pattern", x:580, y:145, r:10, confidence:"85%", era:"2025—", status:"named cost", privacy:"public",
        summary:"Desire is generated by distance; reaching a goal quiets the exact engine that produced the drive toward it. Named as a real structural cost of pothos, not a failure at being happy.",
        source:"“‘Never happy, only content’ is the structural cost of the drive, not a failure at being happy.”",
        sourceMeta:"Goa / conviction session · self-named pattern",
        note:"He states this while living circumstances he once only imagined — the gap is reported first-person, not inferred.",
        relations:[["pothos","costs"],["agency","tempers"]] },
      { id:"hierarchy-question", label:"WHAT DOES INFLUENCE MEAN?", type:"question", x:410, y:85, r:9, confidence:"100%", era:"2026", status:"open", privacy:"public",
        summary:"A contradiction he names himself and hasn't resolved: hierarchy is treated as an organizing convenience, not a legitimate measure of value — yet the stated vision is to be among the most influential people on the planet, an explicitly ranked kind of impact.",
        source:"“For 100 to be a hundred, it needs a hundred ones. Without even one, it ceases being a hundred.”",
        sourceMeta:"Vault gap log · unresolved, held open on purpose",
        note:"Kept as an open question rather than papered over — one of the more honest unresolved tensions in the archive.",
        relations:[["glory","complicates"],["agency","complicates"]] },
      { id:"solitude", label:"SOLITUDE AS INFRASTRUCTURE", type:"pattern", x:225, y:415, r:9, confidence:"90%", era:"2026", status:"tested", privacy:"public",
        summary:"A repeated, tested finding, not a preference: high-stimulation, low-autonomy environments degrade focus and sleep; roughly 90% solitude to 10% socializing is where consistency actually holds.",
        source:"“I'm my best version when I'm like 90% in solitude.”",
        sourceMeta:"ADHD / solitude session · repeated across relocations",
        note:"Framed by him explicitly as infrastructure to protect, not an antisocial trait to justify.",
        relations:[["adhd","stabilizes"],["preparation","enables"]] },
      { id:"voices", label:"TWO VOICES", type:"pattern", x:255, y:270, r:8, confidence:"84%", era:"2026", status:"active tension", privacy:"public",
        summary:"A measured, curious philosopher-architect and an explosive hype-man survivor, both authentic, in permanent tension. The second voice supplies the energy to break through inertia; it also makes promises the steadier voice can't always keep.",
        source:"“Capture Voice 2's energy but translate it into concrete small commitments, don't dampen it.”",
        sourceMeta:"Cognitive operating manual · self-observed split",
        note:"Both voices are held as genuinely his — this isn't framed as a true self versus a mask.",
        relations:[["preparation","destabilized by"],["adhd","expressed through"]] },
      { id:"locked-a", label:"PRIVATE PERSON", type:"locked", x:268, y:354, r:9, redactionWidth:58, privacy:"locked" },
      { id:"locked-b", label:"PRIVATE PERSON", type:"locked", x:212, y:490, r:7, redactionWidth:46, privacy:"locked" },
      { id:"locked-c", label:"PRIVATE PERSON", type:"locked", x:696, y:115, r:9, redactionWidth:70, privacy:"locked" },
      { id:"locked-d", label:"PRIVATE PERSON", type:"locked", x:572, y:475, r:8, redactionWidth:54, privacy:"locked" },
      { id:"locked-e", label:"PRIVATE PERSON", type:"locked", x:420, y:182, r:6, redactionWidth:40, privacy:"locked" },
      { id:"locked-f", label:"PRIVATE PERSON", type:"locked", x:832, y:352, r:5, redactionWidth:36, privacy:"locked" },
      { id:"locked-g", label:"PRIVATE PERSON", type:"locked", x:150, y:238, r:6, redactionWidth:42, privacy:"locked" },
      { id:"locked-h", label:"PRIVATE PERSON", type:"locked", x:790, y:612, r:5, redactionWidth:34, privacy:"locked" }
    ];

export const publicEdges = [
  ["c2x","agency","expresses"],["c2x","information-gap","closes"],
  ["c2x","cloud-consciousness","shares method with"],["c2x","anrxyst","shares world-building with"],
      ["agency","preparation","protects"],["agency","pothos","directs"],["agency","glory","pursues"],
      ["preparation","adhd","scaffolds"],["preparation","consciousness","creates"],
      ["pothos","manifestation","ritualized as"],["pothos","glory","propels"],
      ["manifestation","synchronicity","reads as evidence"],["spiral","movement","interrupted by"],
      ["agency","fallout","expressed as"],["agency","anrxyst","expressed as"],["fallout","sound","embodies"],
      ["anrxyst","information-gap","closes"],["information-gap","consciousness","motivates"],
      ["consciousness","self-model-gap","admits"],
      ["consciousness","cloud-consciousness","is v0 of"],["cloud-consciousness","singularity","aims toward"],
      ["cloud-consciousness","information-gap","upstream of"],
      ["hermetic-philosophy","manifestation","grounds"],["hermetic-philosophy","synchronicity","grounds"],
      ["hermetic-philosophy","singularity","extends into"],
      ["self-belief-scaling","hermetic-philosophy","applies"],["self-belief-scaling","kanye","evidenced by"],
      ["kanye","anrxyst","models"],["kanye","alexander","mirrors"],["alexander","pothos","named after"],
      ["pothos","non-arrival","costs"],["non-arrival","agency","tempered by"],
      ["glory","hierarchy-question","complicates"],["agency","hierarchy-question","complicates"],
      ["adhd","solitude","stabilized by"],["solitude","preparation","enables"],
      ["adhd","voices","expressed through"],["voices","preparation","destabilizes"],
      ["massive-action","preparation","interrupts"],["massive-action","cloud-consciousness","makes exception for"],
      ["multidimensional-self","hermetic-philosophy","extends"],["multidimensional-self","manifestation","frames"],
      ["multidimensional-self","predestination","opens into"],["multidimensional-self","illusion-not-fake","bounded by"],
      ["predestination","hermetic-philosophy","interprets through"],["illusion-not-fake","hermetic-philosophy","guards against nihilism"],
      ["god-as-ethos","hermetic-philosophy","extends"],["god-as-ethos","singularity","contains"],
      ["aham-brahmasmi","hermetic-philosophy","names unity with"],["aham-brahmasmi","god-as-ethos","identifies with whole"],
      ["information-theory-of-life","singularity","feeds"],["information-theory-of-life","information-gap","seeks to close"],
      ["information-theory-of-life","cloud-consciousness","motivates"],["information-theory-of-life","emergence-entropy","accumulates through"],
      ["emergence-entropy","singularity","builds toward"],["aristocrat-philosophy","consciousness","manufactures conditions for"],
      ["purple","anrxyst","signs"],["purple","kanye","inherits palette from"],
      ["fallout","schranz","built around"],["schranz","klangkuenstler","discovered through"],
      ["klangkuenstler","fallout","catalyzed"],["harvey-specter","manifestation","identity scaffold for"],
      ["harvey-specter","kanye","shares role-model function"],
      ["pothos","cloud-consciousness","aims toward"],["pothos","anrxyst","expressed through"],
      ["pothos","fallout","physicalized through"],["pothos","kanye","recognizes itself in"],
      ["glory","cloud-consciousness","seeks continuity through"],["manifestation","cloud-consciousness","extends into"],
      ["anrxyst","fallout","shares world-building with"]
    ];
