"""Generate the Codex Map wireframe asset with Blender.

The output is deliberately artistic: a lumpy, cleft, brain-like net rather
than an anatomical model. Blender owns the source mesh and topology; the site
receives only compact vertices, edges, and paths for a dependency-free WebGL
renderer.
"""

import json
import math
import os
import random
import sys
from collections import deque

import bpy


def build_mesh():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=4, radius=1.0)
    brain = bpy.context.active_object
    brain.name = "Consciousness_Brain_Net"

    for vertex in brain.data.vertices:
        x, y, z = vertex.co
        longitude = math.atan2(y, x)
        latitude = math.asin(max(-1.0, min(1.0, z)))
        folds = (
            1.0
            + 0.085 * math.sin(5.0 * longitude + 0.45) * math.cos(4.0 * latitude)
            + 0.052 * math.sin(9.0 * longitude - 2.2 * latitude)
            + 0.034 * math.cos(13.0 * longitude + 5.0 * latitude)
        )
        px = x * 5.35 * folds
        py = y * 3.32 * folds
        pz = z * 3.28 * folds

        # A longitudinal cleft suggests two hemispheres without claiming
        # anatomical fidelity. It is most visible from the initial high angle.
        if pz > 0:
            cleft = math.exp(-((py / 0.34) ** 2)) * ((pz / 3.28) ** 2)
            pz -= 0.72 * cleft

        # Flatten the underside slightly and let the temporal area sag.
        if pz < -1.7:
            pz = -1.7 + (pz + 1.7) * 0.62
        pz -= 0.12 * (1.0 - min(1.0, abs(px) / 5.35))
        vertex.co = (px, py, pz)

    brain.data.update()
    return brain


def shortest_path(adjacency, start, target):
    queue = deque([start])
    parent = {start: None}
    while queue:
        current = queue.popleft()
        if current == target:
            break
        for neighbor in adjacency[current]:
            if neighbor in parent:
                continue
            parent[neighbor] = current
            queue.append(neighbor)
    if target not in parent:
        return []
    path = []
    cursor = target
    while cursor is not None:
        path.append(cursor)
        cursor = parent[cursor]
    return list(reversed(path))


def export_asset(brain, output_path):
    mesh = brain.data
    # Runtime coordinates: X is horizontal, Blender Z is vertical, Blender Y
    # becomes depth. Values are rounded to keep the shipped asset compact.
    vertices = [
        [round(vertex.co.x, 4), round(vertex.co.z, 4), round(vertex.co.y, 4)]
        for vertex in mesh.vertices
    ]
    edges = [[edge.vertices[0], edge.vertices[1]] for edge in mesh.edges]
    adjacency = [set() for _ in vertices]
    for first, second in edges:
        adjacency[first].add(second)
        adjacency[second].add(first)

    rng = random.Random(0xC0DEC0DE)
    paths = []
    attempts = 0
    while len(paths) < 44 and attempts < 600:
        attempts += 1
        start = rng.randrange(len(vertices))
        target = rng.randrange(len(vertices))
        ax, ay, _ = vertices[start]
        bx, by, _ = vertices[target]
        if math.hypot(ax - bx, ay - by) < 4.1:
            continue
        path = shortest_path(adjacency, start, target)
        if 8 <= len(path) <= 34:
            paths.append(path)

    boundary_left = sorted(range(len(vertices)), key=lambda index: vertices[index][0])[:90]
    boundary_right = sorted(range(len(vertices)), key=lambda index: -vertices[index][0])[:90]
    axons = []
    for side, candidates in ((-1, boundary_left), (1, boundary_right)):
        rng.shuffle(candidates)
        for index in candidates[:15]:
            x, y, z = vertices[index]
            points = []
            for step in range(11):
                progress = step / 10
                reach = progress * (7.2 + rng.random() * 1.8)
                wave = math.sin(progress * math.pi * (1.5 + rng.random())) * (0.18 + rng.random() * 0.22)
                points.append([
                    round(x + side * reach, 4),
                    round(y + wave + (rng.random() - 0.5) * 0.08, 4),
                    round(z * (1.0 - progress * 0.24) + (rng.random() - 0.5) * 0.06, 4),
                ])
            axons.append(points)

    payload = {
        "vertices": vertices,
        "edges": edges,
        "paths": paths,
        "axons": axons,
        "bounds": [-12.6, 12.6, -3.3, 3.3],
        "generator": "Blender 5.2 / scripts/build-brain-net.py",
        "framing": "artistic association; not anatomy",
    }
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("// Generated by Blender. Re-run scripts/build-brain-net.py to change topology.\n")
        handle.write("export const BRAIN_MESH = ")
        json.dump(payload, handle, separators=(",", ":"))
        handle.write(";\n")


def main():
    args = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    if len(args) != 2:
        raise SystemExit("usage: blender --background --python build-brain-net.py -- OUTPUT_JS OUTPUT_BLEND")
    output_js = os.path.abspath(args[0])
    output_blend = os.path.abspath(args[1])
    brain = build_mesh()
    export_asset(brain, output_js)
    bpy.ops.wm.save_as_mainfile(filepath=output_blend)
    print(f"wrote {output_js}")
    print(f"saved {output_blend}")


main()
