// Generates the beingchay landing (index.html) from the consciousness page.
// The landing IS the map, wearing the space skin: same DOM, same engine, same
// data. Only the shell is copied, and it is copied mechanically so the two can
// never drift apart. Re-run this after editing consciousness/index.html:
//
//   node scripts/build-landing.js
//
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const source = path.join(root, "consciousness", "index.html");
const target = path.join(root, "index.html");

let html = fs.readFileSync(source, "utf8");

const rules = [
  // Space skin on from the first paint, so there is no flash of white paper.
  [/<body class="([^"]*)">/, '<body class="$1 space-mode">'],
  // Shared engine, absolute so it resolves from the site root.
  [/src="\/consciousness\/map-page\.js\?v=phase1-5"/, 'src="/consciousness/map-page.js?v=phase1-5"'],
  // Chapter one plays behind the landing, chapter two behind the map.
  [/src="\.\.\/assets\/smoke-state-2\.mp3"/, 'src="/assets/smoke-state-1.mp3"'],
  // On the landing this switch enters the map. Keep its no-JS fallback honest.
  [/<a class="deep-toggle" id="deep-toggle" href="\?mode=brain" role="switch" aria-checked="false" aria-label="Show the head index">/,
   '<a class="deep-toggle" id="deep-toggle" href="/consciousness/" role="switch" aria-checked="false" aria-label="Enter Cloud Consciousness">'],
  [/<title>[^<]*<\/title>/, "<title>beingchay</title>"],
  [/(<meta name="description" content=")[^"]*(")/,
   '$1The constellation behind Chay: fallout, ANRXYST, C2X, and the light at the centre.$2']
];

const missed = [];
for (const [pattern, replacement] of rules) {
  if (!pattern.test(html)) missed.push(String(pattern));
  html = html.replace(pattern, replacement);
}

// The landing sits at the site root, so every path that walked up out of
// /consciousness/ has to become absolute. Generic on purpose: new links added
// to the map keep working here without touching this script.
html = html.replace(/(src|href)="\.\.\//g, '$1="/');

html = html.replace(
  /^<!doctype html>/i,
  "<!doctype html>\n<!-- GENERATED by scripts/build-landing.js from consciousness/index.html. Do not edit by hand. -->"
);

fs.writeFileSync(target, html);

console.log("wrote index.html:", fs.statSync(target).size, "bytes");
if (missed.length) {
  console.error("RULES THAT MATCHED NOTHING (the source markup moved):");
  for (const rule of missed) console.error("  " + rule);
  process.exit(1);
}
console.log("all", rules.length, "rewrite rules applied");
